IF1
	INCLUDE C:\TASM\proj\MACROS.MAC
ENDIF

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE

PUBLIC DISPLAY_AX
	
	;DISPLAYS AX REGISTER CONTENT
	DISPLAY_AX PROC NEAR
		PUSHALL
		
		MOV BX,10
		XOR CX,CX
		
		AGAIN:  XOR DX,DX
				DIV BX		;AX = AX/10, DX = AX%10
				PUSH DX		;STORE AX%10
				INC CX		;INCREASE NR OF DIGITS
				CMP AX,0
				JNZ AGAIN
				
		SHOW:   POP DX		;RETRIEVE DIGIT
				ADD DX,'0'	;MAKE DIGIT PRINTABLE
				MOV AH,02H
				INT 21H
				LOOP SHOW
				
		POPALL
		RET
	DISPLAY_AX ENDP	
CODE ENDS
END DISPLAY_AX