IF1
	INCLUDE C:\TASM\COL\MAXIM\MACROS.MAC
ENDIF

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE
PUBLIC CIT_SIR

	;DS:BX SIRUL IN CARE CITESTI,DS:SI UNDE RETURNEZI LUNGIMEA SIRULUI
	
	CIT_SIR PROC NEAR
		PUSHALL
		
		XOR DI,DI
		
		AGAIN:  MOV AH,01H;
				INT 21H;READ CHAR IN AL
				
				CMP AL,13;FIND IF ENTER
				JE FINISH
				
				SUB AL,'0';MAKE AL NUMBER
				MOV [BX+DI],AL;STORE THE NUMBER
				INC DI
				JMP AGAIN
		
		
		FINISH: MOV CX,DI
				MOV [SI],CL
		POPALL
		RET
	CIT_SIR ENDP
CODE ENDS

END CIT_SIR