IF1
	INCLUDE C:\TASM\COL\HERON\MACROS.MAC
ENDIF

DATA SEGMENT PARA PUBLIC 'DATA'
	TWO DQ 2.0
	PREC DQ 10000.0
	WORD_VAR DW ?
	REAL_AREA DQ ?
	READ_MESSAGE DB 10,13,'PLEASE INPUT A TRIANGLE SIZE:$'
	DISPLAY_MESSAGE DB 10,13,'THE AREA IS $'
	LAT DW ?,?,?;SIZE OF LATURI
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
.8087
ASSUME CS:CODE, DS:DATA
EXTRN READ_AX:NEAR
EXTRN DISPLAY_AX:NEAR

	MAIN PROC FAR
		INIT_DOS
		
		MOV AX,DATA
		MOV DS,AX;INIT DS WITH DATA
		
		MOV CX,3;THREE READS
			
		XOR SI,SI
	
		READ_LP:STRING_TO_ECRAN READ_MESSAGE
				CALL READ_AX;READ IN AX THE NUMBER
				MOV LAT[SI],AX
				ADD SI,TYPE LAT;INCREASE INDEX
				LOOP READ_LP
			
		;ALL THE LATURA SIZEZ ARE FINISHED READING HERE
		FINIT;INITIALIZE COPROC
		
		FILD LAT[0]
		FILD LAT[2]
		FILD LAT[4]
		
		FADD
		FADD
		
		FLD1
		FLD TWO
		FDIV
		FMUL;ON TOS IS THE SEMIPERIMETRU
		
		FST REAL_AREA
		FWAIT
		
		MOV CX,3
		XOR SI,SI
		NEXT:   FLD REAL_AREA
				FILD LAT[SI]
			    ADD SI,TYPE LAT
				FSUB
				FMUL
				FWAIT
				LOOP NEXT
		
		STRING_TO_ECRAN DISPLAY_MESSAGE
		
		FSQRT
		FST REAL_AREA
		FIST WORD_VAR
		FWAIT
		MOV AX,WORD_VAR;AX STORES INTEGER PART (WHICH MAY BE ROUNDED UP)
		
		
		FILD WORD_VAR
		FSUB
		FMUL PREC
		FIST WORD_VAR
		FWAIT;prepare after virgula part
		MOV BX,WORD_VAR
		
		CMP BX,07FFFH;CHECK IF IT WAS UP OR DOWN ROUNDING
		JB GATA
		
		DEC AX;WAS ROUND UP
		FADD PREC
		FIST WORD_VAR
		FWAIT
		MOV BX,WORD_VAR
		
		GATA:
		CALL DISPLAY_AX;show integer part	
		
		MOV DL,'.'
		MOV AH,02H
		INT 21H
		
		
		MOV AX,BX
		CALL DISPLAY_AX;show decimal part
		
		
		RET
	MAIN ENDP
CODE ENDS
END MAIN