DATA1 SEGMENT PARA PUBLIC 'DATA'
	sArray DB "Ana are mere"
	sLen   DB $-sArray
	sPtr   DD sArray
DATA1 ENDS

DATA2 SEGMENT PARA PUBLIC 'DATA'
	dArray DB 100 DUP(?)
	dPtr   DD dArray
DATA2 ENDS

CODE SEGMENT PARA PUBLIC 'CODE'

START PROC FAR
	PUSH DS
	XOR AX,AX
	PUSH AX
	
	LDS
START ENDP
CODE ENDS
END START