; Program that determines the area of a circle with the radius R
; And volume of a sphere with radius R
DATE SEGMENT PARA 'DATA' ;SEGMENT
RADICAL DQ ?
TREI DD 3.0
DATE ENDS
COD SEGMENT PARA 'CODE'
.8087
CALCUL PROC FAR ;
 ASSUME CS:COD, DS: DATE
 PUSH DS ; PREPARE
 XOR AX, AX ; STACK FOR
 PUSH AX ; DOS RETURN
 MOV AX, DATE ; LOADING DS
 MOV DS, AX ; WITH DATA SEGMENT 
 FINIT ;COPROCESOR INITIALIZATION
 FLD1
 FDIV TREI
 F2XM1
 FLD1
 FADD
 FSTP RADICAL
 FWAIT ;SYNCHRONIZATION
  ; VOLUM ADDRSS IN SI
 
 RET
CALCUL ENDP ; END PROCEDURE
COD ENDS ; END CODE SEGMENT
 END CALCUL ; PROGRAM END 