MAX_LEN_SIR EQU 100

IF1
	INCLUDE C:\TASM\COL\MAXIM\MACROS.MAC
ENDIF

DATA SEGMENT PARA PUBLIC 'DATA'
	SIR DB MAX_LEN_SIR DUP(?)
	SIR_LEN DB ?
	MAX DB ?
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA

EXTRN CIT_SIR:NEAR
EXTRN FIND_MAX:NEAR

	MAIN PROC FAR
		DOS_INIT
		MOV AX,DATA
		MOV DS,AX
		
		LEA BX,SIR
		LEA SI,SIR_LEN
		CALL CIT_SIR;DS:BX SIRUL IN CARE SE CITESTE, DS:SI LUNGIMEA SIRULUI RETURNATA
		
		LEA DI,MAX
		CALL FIND_MAX;DS:BX SIRUL, DS:SI LUNGIMEA, DS:DI UNDE RETURNEZI MAXIMUL
		
		MOV AH,02H
		MOV DL,MAX
		ADD DL,'0';MAKE DL CHAR
		INT 21H
		
		RET
	MAIN ENDP
CODE ENDS
END MAIN