LUNG_SIR_MAX EQU 10

DATA SEGMENT PARA PUBLIC 'DATA'
	SIR DB LUNG_SIR_MAX DUP(?)
	SIR_LEN DB ?
	MINIM DB ?
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA

PUBLIC SIR_LEN

EXTRN CITIRE_SIR:NEAR

	MAIN PROC FAR
		PUSH DS
		PUSH 0	;PREPARE RETURN TO OS
		MOV AX,DATA
		MOV DS,AX;PREPARE DS
		
		LEA BX,SIR
		MOV CX,LUNG_SIR_MAX
		
		CALL CITIRE_SIR
		
		XOR SI,SI
		MOV AX,0FFFFH;FOR MINIM 
		
		AGAIN:  CMP SIR[SI],AL
				JNB NOT_BELOW
				MOV AL,SIR[SI]
				
				NOT_BELOW:
				INC SI
				LOOP AGAIN
		
		MOV MINIM,AL
				
		MOV AH,02H
		MOV DL,MINIM
		ADD DX,'0';PREPARE ASCII
		INT 21H
				
		RET
	MAIN ENDP
CODE ENDS
END MAIN