CODE SEGMENT PARA PUBLIC 'code'
ASSUME CS:CODE, DS:CODE
org 100h
START:
	DAT1 DW 3,400H
	DAT2 DB 3,14/5,1,2+5
	STRING DB 'stringsb'
	PSTRING DW STRING
	TRICK DW 2 DUP (4,1)
CODE ends
	end START

