DATA SEGMENT PARA PUBLIC 'DATA'
NO1 DD 17.6
NO2 DD -23.5
NO3 DW 100
NO4 DW -100
DATA ENDS
CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
 PUSH DS
 XOR AX,AX
 PUSH AX
MOV AX,DATA
MOV DS,AX
;OTHER PROGRAM INSTRUCTIONS
RET
START ENDP
CODE ENDS
END START 
