;numarul de vocale dintr-un text
;transforma si caracterele mici in caractere mari

IF1 
	INCLUDE C:\TASM\COL\VOWEL\MACROS.MAC
ENDIF

DATA SEGMENT PARA PUBLIC 'DATA'
	TEXT_MAX_APPROVED DB TEXT_MAX_LEN
	TEXT_LEN DB ?
	TEXT DB TEXT_MAX_LEN+1 DUP('0')
	NR_VOWELS DW ?
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA

EXTRN COUNT_VOWELS:NEAR
EXTRN READ_TEXT:NEAR
EXTRN DISPLAY_ALL:NEAR	
EXTRN SWAP_CASES:NEAR

	MAIN PROC FAR
		INIT_DOS
		MOV AX,DATA
		MOV DS,AX;INITIALIZE DS
		
		LEA DX,TEXT_MAX_APPROVED
		CALL READ_TEXT
		
		LEA DX,TEXT_LEN
		LEA BX,NR_VOWELS
		CALL COUNT_VOWELS
		
		CALL SWAP_CASES
		
		LEA DX, TEXT
		XOR BX,BX
		MOV BL,TEXT_LEN
		ADD BX,DX
		MOV BYTE PTR [BX],'$'
		LEA BX,NR_VOWELS
		CALL DISPLAY_ALL
		
		RET
	MAIN ENDP
	
CODE ENDS
END MAIN